fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /

media:
    resource: "@MediaBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
