user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /admin

media:
    resource: "@MediaBundle/Controller/"
    type:     annotation
    prefix:   /admin

app:
    resource: @AppBundle/Controller/
    type:     annotation
