# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                check_path: fos_user_security_check
                login_path: fos_user_security_login
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: /admin
            logout:
                path:    /admin/logout
                target:    /
            anonymous:    true

    access_control:
        - { path: ^/admin/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_ADMIN }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/user, role: ROLE_ADMIN }
        - { path: ^/admin, role: ROLE_USER }
