# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    rs.facebook:
        class: AppBundle\Services\RSFacebook
    rs.google:
        class: AppBundle\Services\RSGoogle
    rs.twitter:
        class: AppBundle\Services\RSTwitter
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
