services:
    login_listener:
        class: 'UserBundle\Listener\LoginListener'
        arguments: ['@security.context', '@doctrine']
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }

    user.registration.form.type:
        class: 'UserBundle\Form\Type\RegistrationFormType'
        tag:
            - { name: 'form.type', alias: 'acme_user_registration' }
