services:
    login_listener:
        class: 'UserBundle\Listener\LoginListener'
        arguments: ['@security.context', '@doctrine']
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }

    acme_user.registration.form.type:
        class: 'UserBundle\Form\Type\RegistrationFormType'
        tags:
            - { name: form.type, alias: acme_user_registration }