<?php

namespace MediaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClockRepository extends EntityRepository
{
}
